#!/usr/bin/env python
"""CLI wrapper for the CoreConfig sensitivity sweep (Task 1).

Runs the Morris elementary-effects screen implemented in
``aptadynamik.observer.sensitivity`` and writes the ranked report to
``results/sensitivity/morris.json`` and ``docs/sensitivity_analysis.md``.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
for candidate in (REPO_ROOT, SRC_ROOT):
    text = str(candidate)
    if text not in sys.path:
        sys.path.insert(0, text)

from aptadynamik.observer.sensitivity import enumerate_parameters, run_sweep  # noqa: E402

DEFAULT_TRAJECTORIES = 16
DEFAULT_SEED = 17
RESULTS_PATH = Path("results/sensitivity/morris.json")
DOC_PATH = Path("docs/sensitivity_analysis.md")


def _build_payload(result) -> dict:
    inv = enumerate_parameters()
    ranked_names = sorted(inv.free, key=lambda name: result.indices[name], reverse=True)
    return {
        "method": result.method,
        "default_separation": result.default_separation,
        "sign_stability": result.sign_stability,
        "free": inv.free,
        "derived": inv.derived,
        "structural": inv.structural,
        "bounds": {name: list(result.bounds[name]) for name in inv.free},
        "ranked": [
            {
                "parameter": name,
                "mu_star": result.indices[name],
                "mu": result.mu[name],
                "sigma": result.sigma[name],
            }
            for name in ranked_names
        ],
    }


def _write_doc(payload: dict, path: Path) -> None:
    lines = [
        "# PRAMA CoreConfig Sensitivity Analysis",
        "",
        "Generated by `scripts/prama_sensitivity_sweep.py`. Implementation lives in",
        "`src/aptadynamik/observer/sensitivity.py`.",
        "",
        "## Target Functional",
        "",
        "`separation(cfg) = mean_integrity(A_varied, t in [60,80]) - mean_integrity(B_monotonic, t in [60,80])`,",
        "computed by stepping both deterministic scenarios from `verification/scenarios.py` under the",
        "given `cfg` (preserving the scenarios' `regime_geometry.lambda_recovery=0.10`,",
        "`lambda_gain=0.03` setup). Positive separation means the varied/clean trajectory stays",
        "viable while the monotonic-stress trajectory loses integrity.",
        "",
        "## Parameter Classes",
        "",
        "### Free Parameters",
        "",
    ]
    lines.extend(f"- `{name}`" for name in payload["free"])
    lines.extend(
        [
            "",
            "### Structural Parameters",
            "",
            "Integer/window fields, `dt`, and the nested `regime_geometry` block are held fixed.",
            "`regime_geometry` is out of scope for this v1 sweep.",
            "",
        ]
    )
    lines.extend(f"- `{name}`" for name in payload["structural"])
    lines.extend(["", "### Derived Parameters", ""])
    lines.extend(f"- `{name}`" for name in payload["derived"])
    lines.extend(
        [
            "",
            "Derived parameters are never perturbed directly; each sampled configuration rebuilds",
            "`CoreConfig` from source fields so `__post_init__` recomputes them.",
            "",
            "## Morris Screening Results",
            "",
            "| rank | parameter | mu_star | sigma | mu |",
            "| ---: | --- | ---: | ---: | ---: |",
        ]
    )
    for rank, row in enumerate(payload["ranked"], start=1):
        lines.append(
            f"| {rank} | `{row['parameter']}` | {row['mu_star']:.8g} | {row['sigma']:.8g} | {row['mu']:.8g} |"
        )
    reading = (
        "the clean-vs-collapse separation is robust across the +/-50% neighbourhood."
        if payload["sign_stability"] >= 0.8
        else "the clean-vs-collapse separation is fragile outside a narrow band around the defaults."
    )
    lines.extend(
        [
            "",
            "## Sign Stability",
            "",
            f"- Default separation: `{payload['default_separation']:.8g}`",
            f"- Fraction of sampled configurations preserving the default sign: `{payload['sign_stability']:.6f}`",
            f"- Reading: {reading}",
            "",
            "## Modeling Defaults Flagged For Review",
            "",
            "- Range fraction: +/-50% around `CoreConfig` defaults (`RANGE_FRACTION` in `sensitivity.py`).",
            "- Natural lower floor for nonnegative parameters: `0.0`.",
            "- Ratio/probability fields additionally clamped to an upper bound of `1.0`: "
            "`accel_smooth`, `pre_collapse_lambda_ratio`.",
            "- Target functional: tail-window (`t in [60,80]`) integrity separation between",
            "  `A_varied` (clean) and `B_monotonic` (stress).",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_outputs(result, output: Path, doc: Path) -> dict:
    payload = _build_payload(result)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    _write_doc(payload, doc)
    return payload


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run the PRAMA CoreConfig Morris sensitivity sweep.")
    parser.add_argument("--trajectories", type=int, default=DEFAULT_TRAJECTORIES)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--output", type=Path, default=RESULTS_PATH)
    parser.add_argument("--doc", type=Path, default=DOC_PATH)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    result = run_sweep(n_trajectories=args.trajectories, seed=args.seed)
    write_outputs(result, args.output, args.doc)
    print(f"method: {result.method}")
    print(f"default_separation: {result.default_separation:.6f}")
    print(f"sign_stability: {result.sign_stability:.6f}")
    print(f"wrote {args.output}")
    print(f"wrote {args.doc}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
